### ISSUE TITLE
JOSS review

### ISSUE THREAD

**Issue by Fil** [Yomguithereal/talisman#172]
All set [for my review](https://github.com/openjournals/joss-reviews/issues/2405) except this point:
* the guidelines ask us to verify _**State of the field:** Do the authors describe how this software compares to other commonly-used packages?_ => This seems to be lacking at the moment. (Not sure if that is what you mean in #170)

(It would also be great to have the possibility of a root entry point #10, but not a blocker: the curent installation process is functional and well documented).

**Comment by Yomguithereal** [comment]
Hello @Fil. #170 is not related to this I think. I was just hinting at the fact that this library can be used to perform actual precision/recall benchmarks etc. of various methods, something which is more rarely done in this field than in others because of the lack of unified interface such as what this lib offers. (This is off-topic but I am currently building a database of name variants to run such a benchmark with phonetic algorithms).

As someone indicated also in the pre-review, the paper lacks of pointers towards other similar libraries, in JS or other languages and so I intend to add some links soon. I just want to know if I can do this now or if I should wait for you and the other reviewer to first iterate once on the review.

For instance I would like to list [abydos](https://pypi.org/project/abydos/) or things like [java-string-similarity](https://github.com/tdebatty/java-string-similarity) and OpenRefine etc. Would this fit the bill? How many libs/tools should I link to?

**Comment by Fil** [comment]
Feel free to develop your software when you want, there's no "review version" and in any case we can follow the changes. You should "describe how this software compares to other commonly-used packages", it's not for us to be normative about the way you do this (it can be anywhere between an off-hand comment and a full benchmark).

**Comment by Yomguithereal** [comment]
What I don't know yet also is what to do with the exhaustive bibliography of papers implemented by the library. As I understood from the pre-review discussion, I should only list references mentioned by the paper, no? Is there anyway to give some value to the full bibliography?

**Comment by Fil** [comment]
It would be great to have it as a page in the extensive documentation
https://yomguithereal.github.io/talisman/

-- Fil

**Comment by Yomguithereal** [comment]
> It would be great to have it as a page in the extensive documentation

That's a good idea. I will do that, thank you.

**Comment by Yomguithereal** [comment]
Hello @Fil. I have clarified the paper and added something to express #170. I also added, as per your recommendation, the extensive bibliography of implemented methods to the documentation of the library.

**Comment by Fil** [comment]
Great! I've ticked the last box :)
